### ISSUE TITLE
msgpack.exceptions.ExtraData: unpack(b) received extra data.

### ISSUE THREAD

**Issue by alexandermartin** [kuprel/min-dalle#30] opened 2022-06-29 08:04 UTC
Trying to run the sample 

`python3 image_from_text.py --text='a comfy chair that looks like an avocado' --mega --seed=4`

on a new local installation on macOS Monterey yields the following error:

```
detokenizing image
Traceback (most recent call last):
  File "/Users/user/code/min-dalle/image_from_text.py", line 44, in <module>
    image = generate_image_from_text(
  File "/Users/user/code/min-dalle/min_dalle/generate_image.py", line 75, in generate_image_from_text
    image = detokenize_torch(torch.tensor(image_tokens))
  File "/Users/user/code/min-dalle/min_dalle/min_dalle_torch.py", line 108, in detokenize_torch
    params = load_vqgan_torch_params(model_path)
  File "/Users/user/code/min-dalle/min_dalle/load_params.py", line 12, in load_vqgan_torch_params
    params: Dict[str, numpy.ndarray] = serialization.msgpack_restore(f.read())
  File "/usr/local/lib/python3.9/site-packages/flax/serialization.py", line 350, in msgpack_restore
    state_dict = msgpack.unpackb(
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

Is anyone running the sample prompt successfully on Mac? It is unclear to me wether the error is library or data related. Has anyone a similar problem?

**Comment by martinosorb** [comment] 2022-06-29 10:09
Same error on Ubuntu. Haven't had the time to investigate it yet.

**Comment by martinosorb** [comment] 2022-06-29 10:10
Duplicate of #1

**Closed** 2022-06-29 17:12 UTC
